---
name: Docker build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# for each ref (branch/pr) run just the most recent, cancel
# other pending/running ones
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  docker_build:
    name: Build images
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.head.repo.full_name == github.repository
      || contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Filter changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api_app/**/*'
            resource_processor:
              - 'resource_processor/**/*'
            guacamole_server:
              - 'templates/workspace_services/guacamole/guacamole-server/**/*'
            gitea:
              - 'templates/shared_services/gitea/**/*'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: "Test image: api"
        # test should be before build since its docker target
        # is prior to runtime
        if: |
          (steps.filter.outputs.api == 'true'
          || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v2
        with:
          context: ./api_app/
          file: ./api_app/Dockerfile
          outputs: type=local,dest=test-results
          target: test-results
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: "Build image: api"
        if: |
          (steps.filter.outputs.api == 'true'
          || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v2
        with:
          context: ./api_app/
          file: ./api_app/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Build image: resource_processor"
        if: |
          (steps.filter.outputs.resource_processor == 'true'
          || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v2
        with:
          context: ./resource_processor
          file: ./resource_processor/vmss_porter/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Test image: guacamole_server"
        if: |
          (steps.filter.outputs.guacamole_server == 'true'
          || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v2
        with:
          context: ./templates/workspace_services/guacamole/guacamole-server
          file: ./templates/workspace_services/guacamole/guacamole-server/docker/Dockerfile
          outputs: type=local,dest=test-results
          target: test-results
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Build image: guacamole_server"
        if: |
          (steps.filter.outputs.guacamole_server == 'true'
          || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v2
        with:
          context: ./templates/workspace_services/guacamole/guacamole-server
          file: ./templates/workspace_services/guacamole/guacamole-server/docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Build image: gitea"
        if: |
          (steps.filter.outputs.gitea == 'true'
          || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v2
        with:
          context: ./templates/shared_services/gitea
          file: ./templates/shared_services/gitea/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
