---
name: Clean Validation Environments

on:
  schedule:
    # Every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
        with:
          # This is CRITICAL since we're making decisions based on branch existence
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: devops/scripts/clean_ci_validation_envs.sh
